language: python
python:
  - "3.8"

addons:
  apt:
    packages:
      - yamllint

os:
  - linux

install:
  - pip install pyyaml

script:
  - python build.py --dry-run
  - yamllint --no-warnings .
  - git diff --quiet
